version: '3.3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "5000:5000"
    volumes:
      - amine:/var/jenkins_home
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == worker]
volumes:
  amine:
    external: true
